name: ProfileStatus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          config_display: regular
          extras_css: |
            :root {
              --color-calendar-graph-day-L1: #808080;
              --color-accent-fg: #808080;
              --color-accent-emphasis: #808080;
            }
            .header h1, .header h2, .field svg { color: #808080!important; }
